### PR TITLE
Update testing for Boost

### PR DESCRIPTION
**Pull request by hjmallon**
Merge `pkg.template` after Boost NumPy change

### CODE REVIEW

**Review by bkotzz — APPROVED** [review]
The change is fine, but how come it is needed? The only relevant files on the testing branch are the C.I. scripts (travis, appveyor) and the only change to those wasn’t part of the numoy work.

**Comment by hjmallon** [comment]
I thought I had to merge the template branch to get it to test the latest versions? Maybe I'm wrong about that. I wanted to make sure that boost with the numpy change was tested on the ci.

Also there is one change in here which avoids the appveyor long path issues which I came up during ci testing.

**Comment by bkotzz** [comment]
There’s no need to keep every single package’s branch up to date. When you push a branch to run tests, you are merging the pkg.blah branch with your feature branch, and since the only changes on the pkg.blah branch that aren’t in the history tree of mainline hunter are your changes to Travis/appveyor, that’s all that’s brought in. 

But if you need the “line too long” fix for Windows that’s fine.

**Comment by hjmallon** [comment]
OK. Not sure I have fully understood, but I will only push merge template branches in future if there are changes required to the CI configs.

How would I then access the test results for an updated package? Or are they only available in my own `test.X` branch which I make when updating?

**Comment by bkotzz** [comment]
once you push test.X to remote, Travis and appveyor will run automatically. You can just go to their sites and look for the most recent build

**Comment by hjmallon** [comment]
So testing only exists in *my* remote. When I merge here and push to this branch a test is done in cpp-pm remote. I assumed that if I were to merge an update to a package that a test build from within the cpp-pm organisation would be wanted, to confirm that I hadn't messed up my test.X branch.

**Comment by bkotzz** [comment]
It doesn’t really matter which org the testing is done in. I can see builds in your remote and even click on the branches used in those builds, and diff them against whatever I’d like, to make sure the branch being tested makes sense.

And with the free travis/Appveyor builds, builds in a single remote run serially so doing the runs on your own means you won’t wait for anyone else working on hunter at the same time. 

Also nothing abo  it this process is ideal, it’s just how things are currently

**Comment by hjmallon** [comment]
Thanks for taking the time to explain and for your work on this project. I have seen a couple of issues about improving CI but it seems a difficult situation as a full hunter test run would be multiple builds on ~500 projects.

**Pull request merged**
